version: 2.1

orbs:
  slack: circleci/slack@4.10.1

executors:
  node_executor:
    docker:
      - image: cimg/node:16.20

jobs:
  build:
    working_directory: ~/auditjs
    executor: node_executor
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Lint auditjs
          command: yarn lint
      - run:
          name: build
          command: yarn build
      - run:
          name: make test reports directory
          command: mkdir reports
      - run:
          name: test
          command: yarn test-ci
      - run:
          name: code coverage
          command: |
            yarn coverage
            yarn generate-coverage-report
      - store_test_results:
          path: reports
      - store_artifacts:
          path: ./reports/test-results.xml
      - store_artifacts:
          path: ./lcov.info
          prefix: tests
      - run:
          name: dogfood scan
          command: yarn run start ossi --whitelist dev-auditjs.json
      - slack/notify:
          event: fail
          template: basic_fail_1
          branch_pattern: main

  release:
    working_directory: ~/auditjs
    executor: node_executor
    steps:
      - checkout
      - run:
          name: Allow global installs of npm packages
          command: sudo chown -R circleci:circleci /usr/local/lib && sudo chown -R circleci:circleci /usr/local/bin
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build auditjs
          command: yarn build
      - run:
          name: Install publishing packages
          command: yarn global add semantic-release@latest @semantic-release/changelog @semantic-release/git@latest @semantic-release/npm@latest
      - run:
          name: Attempt publish
          command: yarn exec semantic-release
      - slack/notify:
          event: fail
          template: basic_fail_1

workflows:
  version: 2.1
  build_and_release:
    jobs:
      - build:
          context: slack_community_oss_fun
      - release:
          filters:
            branches:
              only: main
          context:
            - auditjs
            - slack_community_oss_fun
          requires:
            - build

  build_nightly:
    triggers:
      - schedule:
          cron: "40 20 * * *"
          filters:
            branches:
              only: main
    jobs:
      - build:
          context: slack_community_oss_fun
